title: Poetry/Poesía.
author: Luis borjas
author_link: https://lfborjas.com
author_description: Spanglish poems 
email: hello@lfborjas.com
description: > # this means to ignore newlines until "baseurl:"
  Original Poetry/poesía original. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://poetry.lfborjas.com" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: zmq5ieg

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: ":title"

# Pagination
paginate: 1

# Sass
sass:
    style: :compressed
